### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by harmydiano** [Haybee96/sbsc#1]
Hello @Haybee96 , Could you explain why you have package.json in each module? And how do we run this app?

**Comment by Haybee96** [comment]
Good evening.

Sorry I didn't explain how to go about the app.

*Explanation*
The app is divided into three(3) different modules (product, orders, and
users).
I have package.json in each module because I did not install the packages
in the root directory. I installed the packages for each module based on
the requirements of the module. It could also be done in the other way by
installing the packages all at once in the root directory.

To run the app
1. Fork the GitHub repository. A folder will be generated which consist of
the main app directory and navigate into the folder directory *cd
folder_name* in your command line where the microservices are listed (the
products and the orders)

2. Navigate into each service (products, orders, users)  and run *npm
install* to get the node_modules folder. For example
In your terminal
     cd products
           npm install

     cd orders
           npm install

     cd users
            npm install


3. The modules have different ports which allow you to have access to the
route. The products run on *http://localhost:5000 <http://localhost:5000>*,
the orders on *http://localhost:6666 <http://localhost:6666>, and users
on http://localhost:5555 <http://localhost:5555>. *I make it like this if
you might need to query each service separately. It can be better though.

4. To test the data, in the products module run;
   *node products.js *for products and test with postman or browser with
the URL: *http://127.0.0.1:5000/api/v1/products
<http://127.0.0.1:5000/api/v1/products>*
   *node orders.js *for orders and test with postman or browser with the
URL: *http://127.0.0.1:6666/api/v1/orders
<http://127.0.0.1:6666/api/v1/orders>*
   *node users.js *for users and test with postman or browser with the
URL: *http://127.0.0.1:5555/api/v1/users
<http://127.0.0.1:5555/api/v1/users>*
